name: image
on:
  push:
    paths:
      - 'static/**'
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Check job status
        run: |
          response=$(curl -s -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=in_progress")
          job_id=$(echo $response | jq -r '.workflow_runs[] | select(.head_sha == ${{ github.sha }} and .name == env.JOB_ID) | .id')
          if [ -n "$job_id" ]; then
            echo "Another instance of the job is already running with ID $job_id. Cancelling it..."
            curl -s -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$job_id/cancel"
          else
            echo "No other instances of the job are currently running."
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.API_KEY }}
          github_token: ${{ secrets.MYGITHUB_TOKEN }}

